#!/usr/bin/env sh

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# shellcheck source=scripts/lib/setup.sh
. "$SCRIPT_DIR/scripts/lib/setup.sh"

SYNC_SCRIPT="$SCRIPT_DIR/sync.sh"
REMOTE_HOST=${REMOTE_HOST:-}
REMOTE_DIR=${REMOTE_DIR:-~/agime}
OPENCLAW_ACCESS_MODE=${OPENCLAW_ACCESS_MODE:-ssh-tunnel}
OVH_ENDPOINT_API_KEY=${OVH_ENDPOINT_API_KEY:-}
TRAEFIK_ACME_EMAIL=${TRAEFIK_ACME_EMAIL:-}
OPENCLAW_DOMAIN=${OPENCLAW_DOMAIN:-}
OPENCLAW_TOKEN=${OPENCLAW_TOKEN:-}

setup_validate
TMP_SYNC_CONFIG=$(setup_build_temp_config)
trap 'rm -f "$TMP_SYNC_CONFIG"' EXIT INT TERM
SYNC_CONFIG_FILE="$TMP_SYNC_CONFIG" SYNC_LOCAL_ENV_FILE="$TMP_SYNC_CONFIG" sh "$SYNC_SCRIPT"
